services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"  # Use Railway's PORT or default to 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:5432}
      - PYTHONUNBUFFERED=1  # Ensures Python output isn't buffered
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3