services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production  # Change this to 'production' for Railway
      - SECRET_KEY=${SECRET_KEY}  # Use an environment variable for the secret key
      - DATABASE_URL=${DATABASE_URL}  # Use Railway's DATABASE_URL
    volumes:
      - .:/app

# Remove the 'db' service and 'volumes' section