[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "flask db upgrade && gunicorn run:app --bind 0.0.0.0:5432"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
internal_port = 5432
protocol = "http"
auto_deploy = true

[services.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3

[services.environment]
FLASK_APP = "run.py"
FLASK_ENV = "production"
DB_POOL_SIZE = "5"
DB_MAX_OVERFLOW = "10"
DB_POOL_TIMEOUT = "30"
DB_POOL_RECYCLE = "1800"