# railway.toml
[project]
name = "your_project_name"

[services]
# Define your web service (Flask app)
[services.web]
name = "web"
type = "web"
env = "production"
start = "gunicorn run:app --bind 0.0.0.0:$PORT"

# Set environment variables individually for the web service
[[services.web.env]]
key = "FLASK_APP"
value = "run.py"

[[services.web.env]]
key = "FLASK_ENV"
value = "production"

[[services.web.env]]
key = "SECRET_KEY"
value = "46dbafcde6cdeda05ffc6c3fad5897fd"

[[services.web.env]]
key = "SQLALCHEMY_DATABASE_URI"
value = "$DATABASE_URL"

[[services.web.env]]
key = "DATABASE_URL"
value = "${{ services.db.url }}"  # Link to the database URL dynamically

# Define the PostgreSQL database service
[services.db]
name = "db"
type = "postgres"

# Optional: Define a release command to apply migrations on deployment
[services.web]
release = "flask db upgrade"