# railway.toml

[project]
name = "taskboard"

# Define your web service (Flask app)
[services.web]
name = "web"
type = "web"
env = "production"
start = "flask db upgrade && gunicorn run:app --bind 0.0.0.0:$PORT"

# Define the PostgreSQL database service
[services.db]
name = "db"
type = "postgres"