# railway.toml
[project]
name = "your_project_name"

[services]
# Define your web service (Flask app)
[services.web]
name = "web"
type = "web"
env = "production"
start = "gunicorn run:app --bind 0.0.0.0:$PORT"

# Set up environment variables for the web service
[[services.web.env]]
FLASK_APP = "run.py"
FLASK_ENV = "production"
SECRET_KEY = "46dbafcde6cdeda05ffc6c3fad5897fd"
SQLALCHEMY_DATABASE_URI = "$DATABASE_URL"
DATABASE_URL = "${{ services.db.url }}"  # This links the database URL dynamically

# Define the PostgreSQL database service
[services.db]
name = "db"
type = "postgres"

[services.web]
release = "flask db upgrade"